debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.test.com.test.spring.spring_test: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restful
    username: root
    password: k1716k
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: true
  sql.init.mode: always
  redis:
    host= localhost
    port= 6379
